import { createHash } from 'node:crypto';
import { readFile, readdir, mkdir, writeFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { join, extname } from 'node:path';
import sharp from 'sharp';

const root = process.cwd(); const file = join(root, 'src/data/catalog.generated.json');
const products = JSON.parse(await readFile(file, 'utf8')); const outDir = join(root, 'public/products'); const variantDir = join(outDir, 'variants'); await mkdir(variantDir, { recursive: true });
const download = async (url) => { for (let attempt = 0; attempt < 3; attempt += 1) { try { const response = await fetch(url, { headers: { 'user-agent': 'SantanaFitnessCatalogueMigration/1.0' }, signal: AbortSignal.timeout(30000) }); if (!response.ok) throw new Error(`HTTP ${response.status}`); const type = response.headers.get('content-type') || ''; if (!type.startsWith('image/')) throw new Error(`not an image (${type})`); return Buffer.from(await response.arrayBuffer()); } catch (error) { if (attempt === 2) console.warn(`Image unavailable: ${url} (${error.message})`); } } return null; };
const queue = products.flatMap((product) => product.images.map((image, index) => ({ product, image, index }))); const worker = async () => { while (queue.length) { const item = queue.shift(); if (!item) return; const { product, image, index } = item; let local = image.localOriginal; let bytes = local && existsSync(join(root, 'public', local.replace(/^\//, ''))) ? await readFile(join(root, 'public', local.replace(/^\//, ''))) : null; if (!bytes && image.originalSrc) { bytes = await download(image.originalSrc); if (bytes) { const extension = extname(new URL(image.originalSrc).pathname).toLowerCase().replace(/[^a-z]/g, '') || 'jpg'; const filename = `${product.slug}${index ? `-${index + 1}` : ''}.${extension === 'jpeg' ? 'jpg' : extension}`; await writeFile(join(outDir, filename), bytes); local = `/products/${filename}`; } } if (!bytes) { image.localOriginal = ''; image.src = ''; continue; } try { const metadata = await sharp(bytes).metadata(); if (!metadata.width || !metadata.height || !metadata.format) throw new Error('invalid dimensions'); const hash = createHash('sha256').update(bytes).digest('hex'); image.localOriginal = local; image.src = local; image.width = metadata.width; image.height = metadata.height; image.hash = hash; image.variants = { fallback: [{ src: local, width: metadata.width, height: metadata.height, bytes: bytes.length, mime: `image/${metadata.format}` }] }; for (const width of [640, 1024, 1440].filter((candidate) => candidate < metadata.width)) { const stem = `${product.slug}${index ? `-${index + 1}` : ''}-${width}-${hash.slice(0, 10)}`; const [webp, avif] = await Promise.all([sharp(bytes).resize({ width, withoutEnlargement: true }).webp({ quality: 82 }).toBuffer(), sharp(bytes).resize({ width, withoutEnlargement: true }).avif({ quality: 70 }).toBuffer()]); const webpName = `${stem}.webp`; const avifName = `${stem}.avif`; await Promise.all([writeFile(join(variantDir, webpName), webp), writeFile(join(variantDir, avifName), avif)]); const height = Math.round(width * metadata.height / metadata.width); image.variants.webp = [...(image.variants.webp || []), { src: `/products/variants/${webpName}`, width, height, bytes: webp.length, mime: 'image/webp' }]; image.variants.avif = [...(image.variants.avif || []), { src: `/products/variants/${avifName}`, width, height, bytes: avif.length, mime: 'image/avif' }]; } } catch (error) { console.warn(`Invalid image for ${product.slug}: ${error.message}`); image.localOriginal = ''; image.src = ''; } } };
await Promise.all(Array.from({ length: 6 }, worker));
for (const product of products) for (const image of product.images) image.isPrimary = image === product.images.find((candidate) => candidate.localOriginal) || image.isPrimary;
await writeFile(file, JSON.stringify(products, null, 2));
for (const dir of ['products', 'categories']) { const source = join(root, 'src/content', dir); for (const name of await readdir(source)) if (name.endsWith('.md')) { const slug = name.slice(0, -3); const record = dir === 'products' ? products.find((item) => item.slug === slug) : null; if (record) await writeFile(join(source, name), `---\n${JSON.stringify(record, null, 2)}\n---\n`); } }
await mkdir(join(root, 'reports'), { recursive: true }); await writeFile(join(root, 'reports/media-manifest.json'), JSON.stringify(products.flatMap((product) => product.images.map((image, index) => ({ product: product.slug, order: index, originalUrl: image.originalSrc, localOriginal: image.localOriginal, mime: image.variants.fallback[0]?.mime || null, width: image.width, height: image.height, bytes: image.variants.fallback[0]?.bytes || 0, sha256: image.hash, variants: image.variants, status: image.localOriginal ? 'downloaded' : 'missing' }))), null, 2));
console.log(`Processed media for ${products.length} products.`);
