import { defineCollection, z } from 'astro:content';

const sourceTrace = z.object({ kind: z.enum(['database', 'public-page', 'public-media', 'derived', 'legacy-page']), url: z.string().url().optional(), identifier: z.string().optional(), field: z.string().optional() });
const imageVariant = z.object({ src: z.string(), width: z.number().int().positive(), height: z.number().int().positive(), bytes: z.number().int().nonnegative().optional(), mime: z.string().optional() });
const image = z.object({ originalSrc: z.string(), localOriginal: z.string(), variants: z.object({ avif: z.array(imageVariant).optional(), webp: z.array(imageVariant).optional(), fallback: z.array(imageVariant) }), alt: z.string().min(1), width: z.number().int().positive(), height: z.number().int().positive(), hash: z.string().regex(/^[a-f0-9]{64}$/), isPrimary: z.boolean(), src: z.string().optional(), cutout: z.object({ src: z.string(), variants: z.object({ avif: z.array(imageVariant).optional(), webp: z.array(imageVariant).optional() }).optional(), width: z.number().int().positive(), height: z.number().int().positive(), alpha: z.boolean().optional() }).optional() });
// `slug` is a reserved Astro entry field and is supplied by the filename; the
// generated manifest still carries it for the domain/data contract.
const products = defineCollection({ schema: z.object({ id: z.string(), legacyId: z.number().int(), slug: z.string().optional(), name: z.string().min(1), code: z.string().optional(), price: z.number().positive().optional(), priceFormatted: z.string().min(1).optional(), categorySlugs: z.array(z.string()), summary: z.string().optional(), description: z.string().optional(), features: z.array(z.string()), specifications: z.array(z.object({ label: z.string(), value: z.string(), unit: z.string().optional() })), images: z.array(image), legacyUrls: z.array(z.string()), seo: z.object({ title: z.string().optional(), description: z.string().optional() }).optional(), sourceTrace: z.array(sourceTrace), featured: z.boolean().optional() }) });
const categories = defineCollection({ schema: z.object({ id: z.string(), slug: z.string().optional(), name: z.string().min(1), description: z.string().optional(), legacyUrls: z.array(z.string()), productCount: z.number().int().nonnegative(), sourceTrace: z.array(sourceTrace) }) });
export const collections = { products, categories };
